"""add ai opportunities

Revision ID: 22c60c24a874
Revises: d0d6a163e3c4
Create Date: 2026-09-13 23:10:21.088383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22c60c24a874'
down_revision: Union[str, Sequence[str], None] = 'd0d6a163e3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ai_capability', sa.String(length=100), nullable=False),
    sa.Column('automation_potential', sa.Float(), nullable=True),
    sa.Column('human_involvement', sa.Float(), nullable=True),
    sa.Column('expected_benefit', sa.Float(), nullable=True),
    sa.Column('feasibility', sa.Float(), nullable=True),
    sa.Column('strategic_alignment', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Float(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_ai_opportunities',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('ai_opportunity_id', sa.Integer(), nullable=False),
    sa.Column('impact_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['ai_opportunity_id'], ['ai_opportunities.id'], ),
    sa.PrimaryKeyConstraint('activity_id', 'ai_opportunity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_ai_opportunities')
    op.drop_table('ai_opportunities')
    # ### end Alembic commands ###
