"""add transformation initiatives

Revision ID: 239437abd6d6
Revises: 46e9bc61bc44
Create Date: 2026-09-13 23:24:43.597035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239437abd6d6'
down_revision: Union[str, Sequence[str], None] = '46e9bc61bc44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transformation_initiatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Float(), nullable=True),
    sa.Column('expected_benefit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('initiative_dependencies',
    sa.Column('initiative_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_initiative_id', sa.Integer(), nullable=False),
    sa.Column('dependency_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['depends_on_initiative_id'], ['transformation_initiatives.id'], ),
    sa.ForeignKeyConstraint(['initiative_id'], ['transformation_initiatives.id'], ),
    sa.PrimaryKeyConstraint('initiative_id', 'depends_on_initiative_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('initiative_dependencies')
    op.drop_table('transformation_initiatives')
    # ### end Alembic commands ###
