"""add governance assessments

Revision ID: 46e9bc61bc44
Revises: 1456841c5ae7
Create Date: 2026-09-13 23:21:57.722942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46e9bc61bc44'
down_revision: Union[str, Sequence[str], None] = '1456841c5ae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('governance_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_opportunity_id', sa.Integer(), nullable=False),
    sa.Column('data_risk', sa.Float(), nullable=True),
    sa.Column('privacy_risk', sa.Float(), nullable=True),
    sa.Column('bias_risk', sa.Float(), nullable=True),
    sa.Column('oversight_requirement', sa.String(length=100), nullable=True),
    sa.Column('explainability_requirement', sa.String(length=100), nullable=True),
    sa.Column('security_risk', sa.Float(), nullable=True),
    sa.Column('decision_impact', sa.Float(), nullable=True),
    sa.Column('regulatory_exposure', sa.Float(), nullable=True),
    sa.Column('model_risk', sa.Float(), nullable=True),
    sa.Column('monitoring_requirement', sa.String(length=100), nullable=True),
    sa.Column('overall_risk', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ai_opportunity_id'], ['ai_opportunities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ai_opportunity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('governance_assessments')
    # ### end Alembic commands ###
