"""add ai opportunity initiative links

Revision ID: 7b9104cb8653
Revises: c40d0d5aaf5c
Create Date: 2026-09-21 22:34:04.332431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b9104cb8653'
down_revision: Union[str, Sequence[str], None] = 'c40d0d5aaf5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_opportunity_initiatives',
    sa.Column('ai_opportunity_id', sa.Integer(), nullable=False),
    sa.Column('initiative_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['ai_opportunity_id'], ['ai_opportunities.id'], ),
    sa.ForeignKeyConstraint(['initiative_id'], ['transformation_initiatives.id'], ),
    sa.PrimaryKeyConstraint('ai_opportunity_id', 'initiative_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_opportunity_initiatives')
    # ### end Alembic commands ###
