"""link evidence to ai opportunities

Revision ID: d53d5fc872da
Revises: 239437abd6d6
Create Date: 2026-09-15 22:25:26.401789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd53d5fc872da'
down_revision: Union[str, Sequence[str], None] = '239437abd6d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence', sa.Column('ai_opportunity_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'evidence', 'ai_opportunities', ['ai_opportunity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.drop_column('evidence', 'ai_opportunity_id')
    # ### end Alembic commands ###
